language: generic

sudo: required

services:
  - docker:

before_install:
  - docker build -t lyg0516/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=ture lyg0516/react-test-app npm run test

after_success:
  - docker build -t lyg0516/docker-frontend ./frontend
  - docker build -t lyg0516/docker-backend ./backend
  - docker build -t lyg0516/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push lyg0516/docker-frontend
  - docker push lyg0516/docker-backend
  - docker push lyg0516/docker-nginx